/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.pruebafiguras.Circulo;
import com.mycompany.pruebafiguras.Cuadrado;
import com.mycompany.pruebafiguras.Rectangulo;
import com.mycompany.pruebafiguras.TrianguloRectangulo;

/**
 *
 * @author hinca
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TXTCIR = new javax.swing.JLabel();
        RADIO_CIRCULO = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PERIMETRO_CIRCULO = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AREA_CIRCULO = new javax.swing.JTextField();
        CALCULAR_CIRCULO = new javax.swing.JButton();
        BORRAR_CIRCULO = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        TXTCIR1 = new javax.swing.JLabel();
        BASE_RECTANGULO = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PERIMETRO_RECTANGULO = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        AREA_RECTANGULO = new javax.swing.JTextField();
        CALCULAR_RECTANGULO = new javax.swing.JButton();
        BORRAR_RECTANGULO = new javax.swing.JButton();
        ALTURA_RECTANGULO = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        TXTCIR2 = new javax.swing.JLabel();
        LADO_CUADRADO = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PERIMETRO_CUADRADO = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AREA_CUADRADO = new javax.swing.JTextField();
        CALCULAR_CUADRADO = new javax.swing.JButton();
        BORRAR_CUADRADO = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        TXTCIR3 = new javax.swing.JLabel();
        BASE_TRIANGULOR = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PERIMETRO_TRIANGULOR = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        AREA_TRIANGULOR = new javax.swing.JTextField();
        CALCULAR_TRIANGULOR = new javax.swing.JButton();
        BORRAR_TRIANGULOR = new javax.swing.JButton();
        ALTURA_TRIANGULOR = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        HIPOTENUSA_TRIANGULOR = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TIPO_TRIANGULOR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        TXTCIR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTCIR.setText("CÍRCULO");

        RADIO_CIRCULO.setBackground(new java.awt.Color(51, 51, 51));
        RADIO_CIRCULO.setForeground(new java.awt.Color(255, 255, 255));
        RADIO_CIRCULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RADIO_CIRCULO.setText("RADIO");
        RADIO_CIRCULO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RADIO_CIRCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RADIO_CIRCULOActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PREÍMETRO");

        PERIMETRO_CIRCULO.setEditable(false);
        PERIMETRO_CIRCULO.setBackground(new java.awt.Color(51, 51, 51));
        PERIMETRO_CIRCULO.setForeground(new java.awt.Color(255, 255, 255));
        PERIMETRO_CIRCULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PERIMETRO_CIRCULO.setText("PERÍMETRO CALCULADO");
        PERIMETRO_CIRCULO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PERIMETRO_CIRCULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PERIMETRO_CIRCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETRO_CIRCULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PERIMETRO_CIRCULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERIMETRO_CIRCULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ÁREA");

        AREA_CIRCULO.setEditable(false);
        AREA_CIRCULO.setBackground(new java.awt.Color(51, 51, 51));
        AREA_CIRCULO.setForeground(new java.awt.Color(255, 255, 255));
        AREA_CIRCULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AREA_CIRCULO.setText("ÁREA CALCULADA");
        AREA_CIRCULO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AREA_CIRCULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AREA_CIRCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREA_CIRCULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AREA_CIRCULO))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AREA_CIRCULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CALCULAR_CIRCULO.setBackground(new java.awt.Color(51, 51, 51));
        CALCULAR_CIRCULO.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR_CIRCULO.setText("CALCULAR");
        CALCULAR_CIRCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_CIRCULOActionPerformed(evt);
            }
        });

        BORRAR_CIRCULO.setBackground(new java.awt.Color(51, 51, 51));
        BORRAR_CIRCULO.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR_CIRCULO.setText("BORRAR");
        BORRAR_CIRCULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_CIRCULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(CALCULAR_CIRCULO)
                .addGap(62, 62, 62)
                .addComponent(BORRAR_CIRCULO)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTCIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RADIO_CIRCULO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TXTCIR)
                .addGap(12, 12, 12)
                .addComponent(RADIO_CIRCULO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCULAR_CIRCULO)
                    .addComponent(BORRAR_CIRCULO))
                .addGap(13, 13, 13))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));
        jPanel8.setPreferredSize(new java.awt.Dimension(337, 248));

        TXTCIR1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTCIR1.setText("RECTÁNGULO");

        BASE_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        BASE_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        BASE_RECTANGULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BASE_RECTANGULO.setText("BASE");
        BASE_RECTANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BASE_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BASE_RECTANGULOActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PREÍMETRO");

        PERIMETRO_RECTANGULO.setEditable(false);
        PERIMETRO_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        PERIMETRO_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        PERIMETRO_RECTANGULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PERIMETRO_RECTANGULO.setText("PERÍMETRO CALCULADO");
        PERIMETRO_RECTANGULO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PERIMETRO_RECTANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PERIMETRO_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETRO_RECTANGULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PERIMETRO_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERIMETRO_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ÁREA");

        AREA_RECTANGULO.setEditable(false);
        AREA_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        AREA_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        AREA_RECTANGULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AREA_RECTANGULO.setText("ÁREA CALCULADA");
        AREA_RECTANGULO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AREA_RECTANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AREA_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREA_RECTANGULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AREA_RECTANGULO, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AREA_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CALCULAR_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        CALCULAR_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR_RECTANGULO.setText("CALCULAR");
        CALCULAR_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_RECTANGULOActionPerformed(evt);
            }
        });

        BORRAR_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        BORRAR_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR_RECTANGULO.setText("BORRAR");
        BORRAR_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_RECTANGULOActionPerformed(evt);
            }
        });

        ALTURA_RECTANGULO.setBackground(new java.awt.Color(51, 51, 51));
        ALTURA_RECTANGULO.setForeground(new java.awt.Color(255, 255, 255));
        ALTURA_RECTANGULO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ALTURA_RECTANGULO.setText("ALTURA");
        ALTURA_RECTANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ALTURA_RECTANGULO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTURA_RECTANGULOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(CALCULAR_RECTANGULO)
                .addGap(62, 62, 62)
                .addComponent(BORRAR_RECTANGULO)
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(BASE_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ALTURA_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTCIR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TXTCIR1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BASE_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALTURA_RECTANGULO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCULAR_RECTANGULO)
                    .addComponent(BORRAR_RECTANGULO))
                .addGap(13, 13, 13))
        );

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));
        jPanel11.setPreferredSize(new java.awt.Dimension(337, 248));

        TXTCIR2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTCIR2.setText("CUADRADO");

        LADO_CUADRADO.setBackground(new java.awt.Color(51, 51, 51));
        LADO_CUADRADO.setForeground(new java.awt.Color(255, 255, 255));
        LADO_CUADRADO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LADO_CUADRADO.setText("LADO");
        LADO_CUADRADO.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        LADO_CUADRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LADO_CUADRADOActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PREÍMETRO");

        PERIMETRO_CUADRADO.setEditable(false);
        PERIMETRO_CUADRADO.setBackground(new java.awt.Color(51, 51, 51));
        PERIMETRO_CUADRADO.setForeground(new java.awt.Color(255, 255, 255));
        PERIMETRO_CUADRADO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PERIMETRO_CUADRADO.setText("PERÍMETRO CALCULADO");
        PERIMETRO_CUADRADO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PERIMETRO_CUADRADO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PERIMETRO_CUADRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETRO_CUADRADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PERIMETRO_CUADRADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERIMETRO_CUADRADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ÁREA");

        AREA_CUADRADO.setEditable(false);
        AREA_CUADRADO.setBackground(new java.awt.Color(51, 51, 51));
        AREA_CUADRADO.setForeground(new java.awt.Color(255, 255, 255));
        AREA_CUADRADO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AREA_CUADRADO.setText("ÁREA CALCULADA");
        AREA_CUADRADO.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AREA_CUADRADO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AREA_CUADRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREA_CUADRADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AREA_CUADRADO, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AREA_CUADRADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CALCULAR_CUADRADO.setBackground(new java.awt.Color(51, 51, 51));
        CALCULAR_CUADRADO.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR_CUADRADO.setText("CALCULAR");
        CALCULAR_CUADRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_CUADRADOActionPerformed(evt);
            }
        });

        BORRAR_CUADRADO.setBackground(new java.awt.Color(51, 51, 51));
        BORRAR_CUADRADO.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR_CUADRADO.setText("BORRAR");
        BORRAR_CUADRADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_CUADRADOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CALCULAR_CUADRADO)
                .addGap(62, 62, 62)
                .addComponent(BORRAR_CUADRADO)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTCIR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LADO_CUADRADO, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TXTCIR2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LADO_CUADRADO, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCULAR_CUADRADO)
                    .addComponent(BORRAR_CUADRADO))
                .addGap(13, 13, 13))
        );

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));
        jPanel14.setPreferredSize(new java.awt.Dimension(337, 248));

        TXTCIR3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTCIR3.setText("TRIÁNGULO RECTÁNGULO");

        BASE_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        BASE_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        BASE_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BASE_TRIANGULOR.setText("BASE");
        BASE_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BASE_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BASE_TRIANGULORActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(51, 51, 51));
        jPanel15.setRequestFocusEnabled(false);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PREÍMETRO");

        PERIMETRO_TRIANGULOR.setEditable(false);
        PERIMETRO_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        PERIMETRO_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        PERIMETRO_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PERIMETRO_TRIANGULOR.setText("PERÍMETRO CALCULADO");
        PERIMETRO_TRIANGULOR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PERIMETRO_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PERIMETRO_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PERIMETRO_TRIANGULORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PERIMETRO_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERIMETRO_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(51, 51, 51));
        jPanel16.setPreferredSize(new java.awt.Dimension(150, 54));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ÁREA");

        AREA_TRIANGULOR.setEditable(false);
        AREA_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        AREA_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        AREA_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AREA_TRIANGULOR.setText("ÁREA CALCULADA");
        AREA_TRIANGULOR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AREA_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AREA_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREA_TRIANGULORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AREA_TRIANGULOR, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AREA_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CALCULAR_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        CALCULAR_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        CALCULAR_TRIANGULOR.setText("CALCULAR");
        CALCULAR_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCULAR_TRIANGULORActionPerformed(evt);
            }
        });

        BORRAR_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        BORRAR_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        BORRAR_TRIANGULOR.setText("BORRAR");
        BORRAR_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BORRAR_TRIANGULORActionPerformed(evt);
            }
        });

        ALTURA_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        ALTURA_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        ALTURA_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ALTURA_TRIANGULOR.setText("ALTURA");
        ALTURA_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ALTURA_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTURA_TRIANGULORActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(51, 51, 51));
        jPanel17.setPreferredSize(new java.awt.Dimension(150, 54));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HIPOTENUSA");

        HIPOTENUSA_TRIANGULOR.setEditable(false);
        HIPOTENUSA_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        HIPOTENUSA_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        HIPOTENUSA_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HIPOTENUSA_TRIANGULOR.setText("ÁREA CALCULADA");
        HIPOTENUSA_TRIANGULOR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HIPOTENUSA_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HIPOTENUSA_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIPOTENUSA_TRIANGULORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HIPOTENUSA_TRIANGULOR, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HIPOTENUSA_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));
        jPanel18.setPreferredSize(new java.awt.Dimension(150, 54));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TIPO DE TRIÁNGULO");
        jLabel11.setPreferredSize(new java.awt.Dimension(62, 16));

        TIPO_TRIANGULOR.setEditable(false);
        TIPO_TRIANGULOR.setBackground(new java.awt.Color(51, 51, 51));
        TIPO_TRIANGULOR.setForeground(new java.awt.Color(255, 255, 255));
        TIPO_TRIANGULOR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TIPO_TRIANGULOR.setText("ÁREA CALCULADA");
        TIPO_TRIANGULOR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TIPO_TRIANGULOR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TIPO_TRIANGULOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIPO_TRIANGULORActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TIPO_TRIANGULOR))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TIPO_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CALCULAR_TRIANGULOR)
                .addGap(62, 62, 62)
                .addComponent(BORRAR_TRIANGULOR)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BASE_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ALTURA_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TXTCIR3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(TXTCIR3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BASE_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ALTURA_TRIANGULOR, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCULAR_TRIANGULOR)
                    .addComponent(BORRAR_TRIANGULOR))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RADIO_CIRCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RADIO_CIRCULOActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RADIO_CIRCULOActionPerformed

    private void PERIMETRO_CIRCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETRO_CIRCULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETRO_CIRCULOActionPerformed

    private void AREA_CIRCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREA_CIRCULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREA_CIRCULOActionPerformed

    private void BASE_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BASE_RECTANGULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BASE_RECTANGULOActionPerformed

    private void PERIMETRO_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETRO_RECTANGULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETRO_RECTANGULOActionPerformed

    private void AREA_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREA_RECTANGULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREA_RECTANGULOActionPerformed

    private void LADO_CUADRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LADO_CUADRADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LADO_CUADRADOActionPerformed

    private void PERIMETRO_CUADRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETRO_CUADRADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETRO_CUADRADOActionPerformed

    private void AREA_CUADRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREA_CUADRADOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREA_CUADRADOActionPerformed

    private void ALTURA_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTURA_RECTANGULOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALTURA_RECTANGULOActionPerformed

    private void BASE_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BASE_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BASE_TRIANGULORActionPerformed

    private void PERIMETRO_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PERIMETRO_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PERIMETRO_TRIANGULORActionPerformed

    private void AREA_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREA_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AREA_TRIANGULORActionPerformed

    private void ALTURA_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTURA_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ALTURA_TRIANGULORActionPerformed

    private void HIPOTENUSA_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIPOTENUSA_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HIPOTENUSA_TRIANGULORActionPerformed

    private void TIPO_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIPO_TRIANGULORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TIPO_TRIANGULORActionPerformed

    private void CALCULAR_CIRCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_CIRCULOActionPerformed
        // TODO add your handling code here:
        try{ 
        Circulo circulo= new Circulo(Integer.parseInt(RADIO_CIRCULO.getText()));
        AREA_CIRCULO.setText(String.valueOf(circulo.calcularArea()));
        PERIMETRO_CIRCULO.setText(String.valueOf(circulo.calcularPerimetro()));
        }
        catch (Exception e){
            RADIO_CIRCULO.setText("INVALIDO");;
        
        }
    }//GEN-LAST:event_CALCULAR_CIRCULOActionPerformed

    private void CALCULAR_CUADRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_CUADRADOActionPerformed
        // TODO add your handling code here:
        try{ 
        Cuadrado cuadrado= new Cuadrado(Integer.parseInt(LADO_CUADRADO.getText()));
        AREA_CUADRADO.setText(String.valueOf(cuadrado.calcularArea()));
        PERIMETRO_CUADRADO.setText(String.valueOf(cuadrado.calcularPerimetro()));
        }
        catch (Exception e){
            LADO_CUADRADO.setText("INVALIDO");;
        
        }
        
    }//GEN-LAST:event_CALCULAR_CUADRADOActionPerformed

    private void CALCULAR_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_RECTANGULOActionPerformed
        // TODO add your handling code here:
        try{ 
        Rectangulo rectangulo= new Rectangulo(Integer.parseInt(BASE_RECTANGULO.getText()),Integer.parseInt(ALTURA_RECTANGULO.getText()));
        AREA_RECTANGULO.setText(String.valueOf(rectangulo.calcularArea()));
        PERIMETRO_RECTANGULO.setText(String.valueOf(rectangulo.calcularPerimetro()));
        }
        catch (Exception e){
            BASE_RECTANGULO.setText("INVALIDO");
            ALTURA_RECTANGULO.setText("INVALIDO");
        
        }
    }//GEN-LAST:event_CALCULAR_RECTANGULOActionPerformed

    private void CALCULAR_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCULAR_TRIANGULORActionPerformed
        // TODO add your handling code here:
        try{ 
        TrianguloRectangulo triangulor= new TrianguloRectangulo(Integer.parseInt(BASE_TRIANGULOR.getText()),Integer.parseInt(ALTURA_TRIANGULOR.getText()));
        AREA_TRIANGULOR.setText(String.valueOf(triangulor.calcularArea()));
        PERIMETRO_TRIANGULOR.setText(String.valueOf(triangulor.calcularPerimetro()));
        HIPOTENUSA_TRIANGULOR.setText(String.valueOf(triangulor.calcularHipotenusa()));
        TIPO_TRIANGULOR.setText(triangulor.determinarTipoTriangulo());
        }
        catch (Exception e){
            BASE_TRIANGULOR.setText("INVALIDO");
            ALTURA_TRIANGULOR.setText("INVALIDO");
        
        }
    }//GEN-LAST:event_CALCULAR_TRIANGULORActionPerformed

    private void BORRAR_CIRCULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_CIRCULOActionPerformed
        // TODO add your handling code here:
        AREA_CIRCULO.setText(" ");
        PERIMETRO_CIRCULO.setText(" ");
        RADIO_CIRCULO.setText("RADIO");
    }//GEN-LAST:event_BORRAR_CIRCULOActionPerformed

    private void BORRAR_CUADRADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_CUADRADOActionPerformed
        // TODO add your handling code here:
        AREA_CUADRADO.setText(" ");
        PERIMETRO_CUADRADO.setText(" ");
        LADO_CUADRADO.setText("LADO");
    }//GEN-LAST:event_BORRAR_CUADRADOActionPerformed

    private void BORRAR_RECTANGULOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_RECTANGULOActionPerformed
        // TODO add your handling code here:
        BASE_RECTANGULO.setText("BASE");
        ALTURA_RECTANGULO.setText("ALTURA");
        AREA_RECTANGULO.setText(" ");
        PERIMETRO_RECTANGULO.setText(" ");
    }//GEN-LAST:event_BORRAR_RECTANGULOActionPerformed

    private void BORRAR_TRIANGULORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BORRAR_TRIANGULORActionPerformed
        // TODO add your handling code here:
        BASE_TRIANGULOR.setText("BASE");
        ALTURA_TRIANGULOR.setText("ALTURA");
        HIPOTENUSA_TRIANGULOR.setText(" ");
        TIPO_TRIANGULOR.setText(" ");
        AREA_TRIANGULOR.setText(" ");
        PERIMETRO_TRIANGULOR.setText(" ");
        
    }//GEN-LAST:event_BORRAR_TRIANGULORActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALTURA_RECTANGULO;
    private javax.swing.JTextField ALTURA_TRIANGULOR;
    private javax.swing.JTextField AREA_CIRCULO;
    private javax.swing.JTextField AREA_CUADRADO;
    private javax.swing.JTextField AREA_RECTANGULO;
    private javax.swing.JTextField AREA_TRIANGULOR;
    private javax.swing.JTextField BASE_RECTANGULO;
    private javax.swing.JTextField BASE_TRIANGULOR;
    private javax.swing.JButton BORRAR_CIRCULO;
    private javax.swing.JButton BORRAR_CUADRADO;
    private javax.swing.JButton BORRAR_RECTANGULO;
    private javax.swing.JButton BORRAR_TRIANGULOR;
    private javax.swing.JButton CALCULAR_CIRCULO;
    private javax.swing.JButton CALCULAR_CUADRADO;
    private javax.swing.JButton CALCULAR_RECTANGULO;
    private javax.swing.JButton CALCULAR_TRIANGULOR;
    private javax.swing.JTextField HIPOTENUSA_TRIANGULOR;
    private javax.swing.JTextField LADO_CUADRADO;
    private javax.swing.JTextField PERIMETRO_CIRCULO;
    private javax.swing.JTextField PERIMETRO_CUADRADO;
    private javax.swing.JTextField PERIMETRO_RECTANGULO;
    private javax.swing.JTextField PERIMETRO_TRIANGULOR;
    private javax.swing.JTextField RADIO_CIRCULO;
    private javax.swing.JTextField TIPO_TRIANGULOR;
    private javax.swing.JLabel TXTCIR;
    private javax.swing.JLabel TXTCIR1;
    private javax.swing.JLabel TXTCIR2;
    private javax.swing.JLabel TXTCIR3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
